export type {
  Accent,
  SiteConfig,
  ChampInfo,
  Standing,
  SeasonSummary,
  SeasonPlacements,
  PlacementPerson,
  LeagueSummary,
  Manager,
  ManagerSeason,
  PersonRow,
  WeekMatchup,
  WeekMatchupSide,
} from './lib/types.ts'
export {
  findRepoRoot,
  dataDir,
  loadSummary,
  loadSeasonFile,
  weeklyMatchups,
  personSlug,
  loadPeopleMap,
  peopleByFirstL,
  historicalOnly,
  managersFromSummary,
  formatPts,
} from './lib/data.ts'
